name: Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  typst-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile documents to PDF using Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: doc/hello-rust-world.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Documents
          path: doc/hello-rust-world.pdf
  slidev-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Setup pnpm
        with:
          version: 9

      - name: Get pnpm store directory
        working-directory: ${{ github.workspace }}/slidev
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/slidev
        run: |
          pnpm install
          pnpm exec playwright install

      - name: Export slides to PDF
        working-directory: ${{ github.workspace }}/slidev
        run: pnpm run export

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Slides
          path: slidev/slides-export.pdf

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [typst-compilation, slidev-export]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            hello-rust-world.pdf
            slides-export.pdf
