name: Release PDF
on:
  push:
    tags:
      - "[0-9].[0-9]+.[0-9]+"

jobs:
  typst-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile documents to PDF using Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: doc/hello-rust-world.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Documents
          path: doc/hello-rust-world.pdf
  slidev-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        working-directory: ${{ github.workspace }}/slidev
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/slidev
        run: pnpm install

      - name: Export slides to PDF
        working-directory: ${{ github.workspace }}/slidev
        run: pnpm run export

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Slides
          path: slidev/slides-export.pdf

  release:
    runs-on: ubuntu-latest
    needs: [typst-compilation, slidev-export]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download PDF files
        uses: actions/download-artifact@v4
      - name: Release PDF files
        run: |
          echo "Release PDF files"
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            doc/hello-rust-world.pdf
            slidev/slides-export.pdf
